### ISSUE TITLE
Plz provide the data

### ISSUE THREAD

**Issue by helonin** [rafiibnsultan/GeoSAM#1]
Hello, author! Thank you for publishing this effective research! I am very interested in your research findings, and I would like to reproduce your research code. Could you provide the data (including image, gt, mask and the image_embeddings.h5 file) for this research ? 
And could you inform me about the structure and dimension of the file 'image_embeddings.h5'?
Thanks for your help!

**Comment by rafiibnsultan** [comment]
Hello,
Sorry for the late reply. We plan on sharing the data publicly after acceptance. However, these data were created by using publicly available Shapefiles and aerial images (more details on the paper). You can regenerate the GT, even changing the no. of classes as per your task.

The image embedding file is specific to our case, and may not work for your work.
