### ISSUE TITLE
关于数据集~~~

### ISSUE THREAD

**Issue by WateverOk** [rafiibnsultan/GeoSAM#4]
请问可以提供一下在训练和推理阶段使用的数据集嘛？

**Comment by rafiibnsultan** [comment]
Hi,
Publishing dataset is in our upcoming plans. Meanwhile, you can see the dataset section in the paper, we used public GIS data to get the coordinates of the objects on aerial images to create the datasets. (You can also check the referenced links in the paper to find these files)

**Comment by zzk2021** [comment]
> Hi, Publishing dataset is in our upcoming plans. Meanwhile, you can see the dataset section in the paper, we used public GIS data to get the coordinates of the objects on aerial images to create the datasets. (You can also check the referenced links in the paper to find these files)

hi，do you have any plan to public dataset？I need a benchmark to test my model，thanks
